### PR TITLE
Started frontend and added pages and components

### PR DESCRIPTION
**Pull request by zhimw**
Added the pages user will see when using the react app using React router dom.

- Front page
- Verification page
- Registration page
- Account overview page
- Create new credential page
- Edit credential page

Created header component which will work as a Nav bar.

### CODE REVIEW

**Review by james-labyer — COMMENTED** [review]
@zhimw looks good! A few comments- since we are delegating authentication to a third party, we do not need to provide our own UI components for sign in/ sign up, as Google provides widgets for us to use. In the starter app that Carlos has set up, you can see the Firebase login widget in the demo video and in password_manager/backend/static/script.js . 

Also, the backend will need to be updated to serve the new pages you have created. As it currently stands, the backend will still serve the starter pages that Carlos made.

Looking forward to seeing this in production :-)

**Review by carlosmmc — COMMENTED** [review]
I agree with the comment James left. I pulled the branch and was able to successfully start the frontend, it looks great!! Next time feel free to add some photos in the PR description as well.

image

**Comment by zhimw** [comment]
Updated the homepage with firebaseui widget.
image

**Review by carlosmmc — APPROVED** [review]
woohoo looks great!!

**Pull request merged**
